### ISSUE TITLE
logarithmic + total view + faktor view

### ISSUE THREAD

**Issue by SIRprise** [fabianhinz/rkicasesdashboard#1]
Very nice visuals!
Please make it logarithmic + a view with summed up all bundesländer + a graph with faktor or percentage of difference to day before.
similar to here https://covid-19.openmedical.de/

**Comment by fabianhinz** [comment]
Thanks. The latest commit includes aggregated information at the top of the page. 
- a logarithmic toggle will come
- about the difference to a day before - i'll have a look
![Screenshot 2020-03-27 at 15 09 16](https://user-images.githubusercontent.com/22753474/77764470-fb9de880-703c-11ea-9a60-fd32f1dd006b.png)

**Comment by SIRprise** [comment]
Thanks! (I have my own viewer, but lack of time to improve and redesign it - C# builtin features to visualize these things are limited or at least there is no template (https://github.com/SIRprise/CoronaViewer))

Please have a look to smartphone, too. (size of badges fills the screen on my android)

**Comment by fabianhinz** [comment]
log, axis labels and legends can be turned on if needed

![Screenshot 2020-03-27 at 16 21 29](https://user-images.githubusercontent.com/22753474/77771512-12493d00-7047-11ea-9a03-7e5f9be6040b.png)

**Comment by fabianhinz** [comment]
> Thanks! (I have my own viewer, but lack of time to improve and redesign it - C# builtin features to visualize these things are limited or at least there is no template (https://github.com/SIRprise/CoronaViewer))
> 
> Please have a look to smartphone, too. (size of badges fills the screen on my android)

ah i see. Well the web has some greate component libs. I'm currently using this one https://material-ui.com/

**Comment by fabianhinz** [comment]
@SIRprise have a look at the latest version - it is now possible to:
- activate / deactivate graphs
- select states and see summed up values of the data at the top of the page
- toggle grid layout to inspect a graph more closely

![pwa](https://user-images.githubusercontent.com/22753474/78070669-7c8e1480-739c-11ea-9149-9699878624df.png)

**Comment by fabianhinz** [comment]
i will close this for now - @SIRprise if you have anything else you're welcome to open a new issue
