### ISSUE TITLE
Tooltip cut

### ISSUE THREAD

**Issue by SIRprise** [fabianhinz/rkicasesdashboard#26]
Wenn die Größe des Dashboards (das "Verhältnis") zu schmal gewählt wird, schneidet es die Tooltips ab.
Vermutlich wird es sinnvoller sein, zu den kleineren Diagrammen auch kleinere Tooltips zu machen statt sie nicht mehr abschneiden zu lassen, aber das ist auch künstlerische Freiheit.

![image](https://user-images.githubusercontent.com/5807446/78905320-18471100-7a7e-11ea-9d9b-fe17c3e85775.png)

Bei dem "Verhältnis"-Slider würde ich intuitiv übrigens erwarten, dass es nach links verkleinert und nach rechts vergrößert. Man könnte das aber auch mit einer Beschriftung wie "Komprimierungsfaktor Darstellung" oder etwas in der Art lösen.
Edit: Jetzt habe ich glaube ich doch verstanden, was "Verhältnis" meint - es ist wohl das Verhältnis Höhe/Breite. ok.

**Comment by fabianhinz** [comment]
Das Tooltip halte ich allgemein für zu dominant. Vorschlag: sollte die Höhe des Charts die des Tootlips übersteigen, so werden die Informationen Unterhalb des Charts eingeblendet. 
bzgl. Verhältnis: Da könnte man die Beschriftung anpassen "Verhältnis Höhe/Breite" 🤔

**Comment by SIRprise** [comment]
Tooltip - ja, etwas dominant ist der schon. Das ist letztlich wohl Geschmacksache.
Genau bei der Einblendung darunter als Lösung sehe ich eine Gefahr: Wenn man am unteren Rand eines Tablets einen Datenpunkt antippt müsste man evtl. herunterscrollen um es zu sehen - und das ist womöglich nicht möglich weil man dazu woanders hintippt. Auch am PC: Mausrad nach unten, aber bloß nicht dabei das mouseover (oder h_over?) event verlieren, sonst blendet es sich aus und die Seite scrollt wieder nach oben.

Zur Beschriftung vom Verhältnis kann ich nicht viel sagen. Ich kenne sonst nur Lupen oder andere Zoom-Anzeigen mit + und - die einen ähnlichen Effekt haben, aber es ist halt hier schon ein bisschen was anderes.
