### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by SIRprise** [fabianhinz/rkicasesdashboard#8]
Very good improvements! :-)
I'm glad you changed the confusing percentage symbol for the incidence. I always thought that are the recovered cases. (and I still hope you introduce an percentage or increase-factor-diagram or doubling rate in days)

A small issue still exists:
[https://github.com/fabianhinz/rkicasesdashboard/issues/1#issuecomment-606849566](https://github.com/fabianhinz/rkicasesdashboard/issues/1#issuecomment-606849566)
I guess, you forgot to upload the new changes?
I cannot activate a grid and see this:
![image](https://user-images.githubusercontent.com/5807446/78302337-ddebea00-753a-11ea-947e-d687008b0a65.png)

**Comment by fabianhinz** [comment]
this app actually uses a service worker, to load files faster and request newer files from the server in the background. This means you might see older Versions. **To get the new version** you have to wait ~10 Seconds, close the page and reopen it. 
Why is this app using a service worker - you might ask >> To work offline 🥇 

To minimize this problem I have included a small build/release pipeline via GitHub Actions. This will deploy all merges on master. The short-sha visible on the main page on GitHub is used as the version number in the app as seen on the top right corner of the second screenshot.

![Screenshot 2020-04-03 at 09 43 00](https://user-images.githubusercontent.com/22753474/78336360-875ccb00-758f-11ea-8061-9caa29dc2e27.png)
 

![pwa](https://user-images.githubusercontent.com/22753474/78336057-08679280-758f-11ea-85d6-af71210265af.png)

about your request. I'll leave this open and see what i can do in the comming days

**Comment by SIRprise** [comment]
AAhhh! Very nice! - As you can see: I'm using your app all the time and didn't close it^^
I could even see the summed up diagram now. :-)
Thank you!

**Comment by fabianhinz** [comment]
@SIRprise I just pushed some changes. The most notable is a new toggle to switch between absolute metrics and a percentage value. The later shows the delta between the current day and the day before.

**Comment by SIRprise** [comment]
Da das ohnehin alles deutsch ist wechsel ich mal auf deutsch.

Hab es gestern schon gesehen und freue mich - vor allem die Normalisierung zum Vergleich mit anderen Bundesländern ist nützlich. Ich nutze praktisch nur die "Differenz zum Vortag"-Ansicht. Die absolute Zahl ist ja nicht so nützlich, außer, dass sie Leute erschreckt.
Langsam werden auch bei anderen Projekten zunehmend Diagramme erstellt, die einfache Voraussagen zulassen indem sie die täglichen Änderungen ins Verhältnis setzen.
Hier ist z.B. eine Darstellung die die Verdopplung im Fokus hat (und sie im Tooltip dann genau nennt)
[https://datawrapper.dwcdn.net/CcQTT/8/](https://datawrapper.dwcdn.net/CcQTT/8/)

**Comment by fabianhinz** [comment]
Dann mach ich hier mal wieder auf. 
Daten anzeigen (wie bisher ist das eine), der Erkenntnisgewinn ist dadurch jedoch nicht hoch.
Da sind Modellierungen zur Vorhersage schon angebracht. 👍

**Comment by SIRprise** [comment]
Hmm, ich scheue mich zwar immer davor auf "close" zu klicken, aber meine Anmerkungen waren nun kein "issue", eher ein "feature request" und noch eher einfach eine Inspiration oder eine Art Feedback, auf welche Zahlen und Daten ich selbst so achte. Also alles schick! 👍 

Notiz an mich selbst: Checke mal die Datenquelle, ob bei den verschiedenen Zahlenarten eventuell die recovered rausgerechnet sind sodass das die "active cases" sind.

**Comment by fabianhinz** [comment]
Deshalb gibts nun ein label: "feature request" 😄 
Anmerkungen sind definitiv willkommen!
Mit dem neuesten Commit gibt es nun Balkendiagramme für die Verdopplungszeit. Damit das Diagramm nicht zu arg auf die Volatilität reagiert, wird zu einem Datenpunkt das arithmetische Mittel mit dem Nächstälteren gebildet. mit einem weiteren Datenpunkt in der Vergangenheit wird anschließend der Wachstumsfaktor berechnet.
einbezogene Datenpunkte lassen sich an der Schattierung im Hintergrund erkennen
![image](https://user-images.githubusercontent.com/22753474/78804514-80372200-79c0-11ea-8d62-5b0114d0a704.png)

**Comment by SIRprise** [comment]
👍 zu der coolen neuen Funktion und dem feature request label 😄 

Die Markierung in orange finde ich hingegen irritierend:
Bei mir werden immer die letzten beiden vergangenen vom selektierten markiert. Intuitiv hätte ich gedacht, dass eine Berechnung zwischen dem Aktuellen und dem Vorgängerdatenpunkt gemacht wird und die beiden darum auch markiert werden. Das fände ich auch dann noch ok, wenn zusätzlich vorher noch der Vorvorgänger einbezogen wird. (Es wäre auch ok, wenn dann einfach 3 markiert sind)
Von der Usability ist der Effekt momentan der, dass ich beim Ausprobieren alles versuchte um die aktuellsten beiden Werte zu markieren, um eben den aktuellsten Wert zu bekommen.

Das mit den active cases vermutete ich auch so, bin aber auch unsicher, denn ich hörte auch mal zwischendrin, dass die Zahl der Genesenen pro Tag den der Neuinfektionen übersteigen täte - das müsste man dann ja aber deutlich in den Absolutzahlen sehen. Andererseits hörte ich aus anderer Quelle auch wieder, dass die Zahlen noch steigen täten... So oder so: Zum Zeitpunkt an dem öffentlich gesagt wird, dass es sinkt, können wir es verifizieren.

**Comment by fabianhinz** [comment]
das ist natürlich was dran, was hälst du von folgender Lösung?

![Screen Recording 2020-04-09 at 10 43 24](https://user-images.githubusercontent.com/22753474/78876133-2a5d8b00-7a4f-11ea-8432-65773de04e7b.gif)

**Comment by SIRprise** [comment]
Sehr gut! Evtl. könnte man die beiden vorangegangenen Werte etwas dunkler färben (aber in der gleichen Farbe) als den aktuell selektierten. Damit könnte man etwas besser zeigen, dass mit den vorangegangenen Daten etwas gemacht wird, aber die Selektion trotzdem auf dem Wert liegt über dem der Zeiger ist. Das sind aber wirklich Feinheiten. Auch die gezeigte Lösung gefällt mir schon sehr gut. :-)

**Comment by fabianhinz** [comment]
sofern Feinheiten wenig Aufwand sind, gibts die natürlich recht schnell 🥳 
![image](https://user-images.githubusercontent.com/22753474/78897467-81288c00-7a72-11ea-934c-369377879568.png)

**Comment by SIRprise** [comment]
eigentlich meinte ich von den 3 Balken die beiden links in anderer Farbe, aber so wie jetzt ist auch ok.

**Comment by fabianhinz** [comment]
oh das hatte ich wohl falsch interpretiert.
Die Nachkommastelle halte ich auch für sinnig. Da ich allerdings bei jeder Kachel das gleiche Verhalten anstrebe, würde ich ungern Sonderregelungen für Werte einführen. Für denkbar halte ich bei gesetztem "Anzeige in Prozent" den prozentualen Zuwachs, zusätzlich zum absoluten Wert. Also quasi ein Verhalten wie bei dem Toggle "Legende".

**Comment by fabianhinz** [comment]
> Hmm, ich scheue mich zwar immer davor auf "close" zu klicken, aber meine Anmerkungen waren nun kein "issue", eher ein "feature request" und noch eher einfach eine Inspiration oder eine Art Feedback, auf welche Zahlen und Daten ich selbst so achte. Also alles schick! 👍
> 
> Notiz an mich selbst: Checke mal die Datenquelle, ob bei den verschiedenen Zahlenarten eventuell die recovered rausgerechnet sind sodass das die "active cases" sind.

mit blick auf das RKI-Dashboard: Die recovered sind aus den Zahlen vom RKI nicht herausgerechnet. Sprich - Fälle in der Datengrundlage sind erfasste und nicht aktive Fälle
